name: Build and deploy on Scalingo

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'API/**'
      - 'front-end/**'
      - 'docker/**'
jobs:
  build-deploy-scalingo:
    name: Build and deploy on Scalingo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # From: https://github.com/ad-m/github-push-action
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Build the react app
        run: |
          npm install
          npm run build
        working-directory: ./front-end

      - name: Copy the built code
        run: cp -a front-end/build API
        working-directory: ./

      - name: Recreate branch to make sure we're up to date
        run: |
          git push -d origin deploy-scalingo
          git checkout -b deploy-scalingo
          git push
        working-directory: ./

      - name: Commit and push to deploy branch
        uses: EndBug/add-and-commit@v6
        with:
          add: '--force API/build'
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'deploy-scalingo'
          message: 'Deploying ${{ github.sha }}'
