name: Build only the front and run all docker containers

# Run this workflow every time a new commit pushed to your repository
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'front-end/**'
      - 'docker/docker-compose.yml'
      - 'docker/front.dockerfile'
      - 'docker/nginx.conf'

jobs:
  docker-build:
    # Name the Job
    name: Build only the api and run all docker containers
    # Set the type of machine to run on
    runs-on: self-hosted

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build only the front container using docker-compose
        run: docker-compose build front
        working-directory: ./docker

      - name: Run docker containers
        run: docker-compose up -d
        working-directory: ./docker